server:
  servlet:
    context-path: /cevaja-db-poc
  port: 8081

clima-external-api: https://api.weatherapi.com/v1/current.json?key=7b8fa6a32fab4e5aba7230804231605&q=porto_Alegre&aqi=no

spring:
  datasource:
      url: jdbc:h2:mem:pocdb
      driver-class-name: org.h2.Driver
      username: fundatec
      password: fundatec
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: true